### Importing Necessary Libraries

In [1]:
import pandas as pd 
import plotly.express as px
import matplotlib.pyplot as plt 
import json

### Making browser for loading plots

In [2]:
import plotly.io as pio
pio.renderers.default = 'browser'

### loading Indain states geojson
download link = https://un-mapped.carto.com/tables/states_india/public/map

In [3]:
india_states = json.load(open("states_india.geojson", "r"))

In [4]:
india_states['features'][0]['properties']

{'cartodb_id': 1, 'state_code': 0, 'st_nm': 'Telangana'}

### Mapping Ids with state names

In [5]:
state_id_map = {}
for feature in india_states["features"]:
    feature["id"] = feature["properties"]["state_code"]
    state_id_map[feature["properties"]["st_nm"]] = feature["id"]

In [6]:
state_id_map

{'Telangana': 0,
 'Andaman & Nicobar Island': 35,
 'Andhra Pradesh': 28,
 'Arunanchal Pradesh': 12,
 'Assam': 18,
 'Bihar': 10,
 'Chhattisgarh': 22,
 'Daman & Diu': 25,
 'Goa': 30,
 'Gujarat': 24,
 'Haryana': 6,
 'Himachal Pradesh': 2,
 'Jammu & Kashmir': 1,
 'Jharkhand': 20,
 'Karnataka': 29,
 'Kerala': 32,
 'Lakshadweep': 31,
 'Madhya Pradesh': 23,
 'Maharashtra': 27,
 'Manipur': 14,
 'Chandigarh': 4,
 'Puducherry': 34,
 'Punjab': 3,
 'Rajasthan': 8,
 'Sikkim': 11,
 'Tamil Nadu': 33,
 'Tripura': 16,
 'Uttar Pradesh': 9,
 'Uttarakhand': 5,
 'West Bengal': 19,
 'Odisha': 21,
 'Dadara & Nagar Havelli': 26,
 'Meghalaya': 17,
 'Mizoram': 15,
 'Nagaland': 13,
 'NCT of Delhi': 7}

### Forest cover data released by PIB India

In [7]:
forest_cover_df = pd.read_excel("forest_area.xlsx")

In [8]:
forest_cover_df = forest_cover_df[:35]

In [9]:
forest_cover_df

                    State/UT  Geo_graphical_Area       VDF       MDF        OF
0             Andhra Pradesh              162968   1994.00  13929.00  13861.00
1         Arunanchal Pradesh               83743  21058.00  30176.00  15197.00
2                      Assam               78438   3017.00   9991.00  15304.00
3                      Bihar               94163    333.00   3286.00   3762.00
4               Chhattisgarh              135192   7068.00  32279.00  16370.00
5               NCT of Delhi                1483      6.72     56.60    131.68
6                        Goa                3702    538.00    576.00   1130.00
7                    Gujarat              196244    378.00   5032.00   9516.00
8                    Haryana               44212     28.00    445.00   1130.00
9           Himachal Pradesh               55673   3163.00   7100.00   5180.00
10                 Jharkhand               79716   2601.00   9689.00  11431.00
11                 Karnataka              191791   4533.00  20985.00  13212.00
12                    Kerala               38852   1944.00   9472.00   9837.00
13            Madhya Pradesh              308252   6665.00  34209.00  36619.00
14               Maharashtra              307713   8734.00  20589.00  21475.00
15                   Manipur               22327    905.00   6228.00   9465.00
16                 Meghalaya               22429    560.00   9160.00   7326.00
17                   Mizoram               21081    157.00   5715.00  11948.00
18                  Nagaland               16579   1272.00   4449.00   6530.00
19                    Odisha              155707   7213.00  20995.00  23948.00
20                    Punjab               50362     11.00    793.00   1043.00
21                 Rajasthan              342239     78.00   4369.00  12208.00
22                    Sikkim                7096   1102.00   1551.00    688.00
23                Tamil Nadu              130060   3593.00  11034.00  11792.00
24                 Telangana              112077   1624.00   9119.00  10471.00
25                   Tripura               10486    647.00   5212.00   1863.00
26             Uttar Pradesh              240928   2627.00   4029.00   8162.00
27               Uttarakhand               53483   5055.00  12768.00   6482.00
28               West Bengal               88752   3037.00   4208.00   9587.00
29  Andaman & Nicobar Island                8249   5678.00    683.00    383.00
30                Chandigarh                 114      1.36     13.51      8.01
31               Daman & Diu                 602      1.40     85.56    140.79
32           Jammu & Kashmir              222679   4157.00   8629.00  10873.00
33               Lakshadweep                  30      0.00     16.09     11.01
34                Puducherry                 490      0.00     17.53     35.77

### Mapping Ids with the dataframe State Names

In [10]:
forest_cover_df["id"] =forest_cover_df["State/UT"].apply(lambda x: state_id_map[x])

In [11]:
forest_cover_df

,State/UT,Geo_graphical_Area,VDF,MDF,OF,id
0,Andhra Pradesh,162968,1994.00,13929.00,13861.00,28
1,Arunanchal Pradesh,83743,21058.00,30176.00,15197.00,12
2,Assam,78438,3017.00,9991.00,15304.00,18
3,Bihar,94163,333.00,3286.00,3762.00,10
4,Chhattisgarh,135192,7068.00,32279.00,16370.00,22
5,NCT of Delhi,1483,6.72,56.60,131.68,7
6,Goa,3702,538.00,576.00,1130.00,30
7,Gujarat,196244,378.00,5032.00,9516.00,24
8,Haryana,44212,28.00,445.00,1130.00,6
9,Himachal Pradesh,55673,3163.00,7100.00,5180.00,2
10,Jharkhand,79716,2601.00,9689.00,11431.00,20
11,Karnataka,191791,4533.00,20985.00,13212.00,29
12,Kerala,38852,1944.00,9472.00,9837.00,32
13,Madhya Pradesh,308252,6665.00,34209.00,36619.00,23
14,Maharashtra,307713,8734.00,20589.00,21475.00,27
15,Manipur,22327,905.00,6228.00,9465.00,14
16,Meghalaya,22429,560.00,9160.00,7326.00,17
17,Mizoram,21081,157.00,5715.00,11948.00,15
18,Nagaland,16579,1272.00,4449.00,6530.00,13
19,Odisha,155707,7213.00,20995.00,23948.00,21
20,Punjab,50362,11.00,793.00,1043.00,3
21,Rajasthan,342239,78.00,4369.00,12208.00,8
22,Sikkim,7096,1102.00,1551.00,688.00,11
23,Tamil Nadu,130060,3593.00,11034.00,11792.00,33
24,Telangana,112077,1624.00,9119.00,10471.00,0
25,Tripura,10486,647.00,5212.00,1863.00,16
26,Uttar Pradesh,240928,2627.00,4029.00,8162.00,9
27,Uttarakhand,53483,5055.00,12768.00,6482.00,5
28,West Bengal,88752,3037.00,4208.00,9587.00,19
29,Andaman & Nicobar Island,8249,5678.00,683.00,383.00,35
30,Chandigarh,114,1.36,13.51,8.01,4
31,Daman & Diu,602,1.40,85.56,140.79,25
32,Jammu & Kashmir,222679,4157.00,8629.00,10873.00,1
33,Lakshadweep,30,0.00,16.09,11.01,31
34,Puducherry,490,0.00,17.53,35.77,34

### Plotting Maps with relevant data

In [14]:
fig = px.choropleth(
    forest_cover_df,
    locations="id",
    geojson=india_states,
    color="OF",
    hover_name="State/UT",
    hover_data=["OF"],
    title="Indian OPEN Forest Cover(OF)",
)
fig.update_geos(fitbounds="locations", visible=False)
fig.show()